version: '3.7'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=BuildindingAndCo
    ports:
      - "5579:5432"